# Site settings
title: DLVM
email: team@dlvm.org 
description: >
  Site for DLVM (Deep Learning Virtual Machine), a compiler infrastructure for 
  modern deep learning software.
baseurl: ""
url: "dlvm.org"
permalink: /blog/:title/

# Social media
github_username: dlvm-team

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
